max_velocity = 1.5 #m/s
max_acceleration = 1.25 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.07
    y = 3.36
    angle = 180.0

[end_pose]
    x = 2.02 #FIXME point is from end of floor node to center of robot measured on practice bot
    y = 2.625
    angle = 180.0

[[internal_points]]
    x = 5.4
    y = 4.65

[[internal_points]]
    x = 2.2
    y = 4.42