max_velocity = 2.25 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 1.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 4.7
    y = 0.739702
    angle = 180.0

[end_pose]
    x = 2.02
    y = 1.27 #1.07
    angle = 180.0

[[internal_points]]
    x = 2.7
    y = 1.27