max_velocity = 3.25 #m/s
max_acceleration = 3.25 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.6 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02
    y = 1.07
    angle = 0.0

[end_pose]
    x = 6.77
    y = 1.07 #0.92->1.02
    angle = 0.0

[[internal_points]]
    x = 2.75
    y = 0.75

[[internal_points]]
    x = 5.8
    y = 0.75