max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.5 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 6.9 #7.07
    y = 0.92 #1.07
    angle = 180.0

[end_pose]
    x = 2.12  #2.32 -> 2.47
    y = 1.3  #1.17->1.27->1.4 -> 1.5
    angle = 180.0 

[[internal_points]]
    x = 4.5 
    y = 0.85