max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02
    y = 0.69 #0.53
    angle = 0.0

[end_pose]
    x = 7.07
    y = 0.92 #0.909702
    angle = 0.0

[[internal_points]]
    x = 4.5
    y = 0.752702