max_velocity = 2.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.5 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.07
    y = 2.14
    angle = 180.0

[end_pose]
    x = 2.02
    y = 1.07
    angle = 180.0

[[internal_points]]
    x = 5.5 #guess
    y = 1.07 #guess