max_velocity = 3.25 #m/s 2.75
max_acceleration = 3.0 #m/s 2.75
start_velocity = 0.0 #m/s
end_velocity = 0.75 #m/s 0.6
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02
    y = 0.69 #0.53
    angle = 0.0

[end_pose]
    x = 6.77 #7.00
    y = 2.54 #2.34->2.44->2.54->2.64->2.54
    angle = 0.0

[[internal_points]]
    x = 5.8
    y = 0.85

[[internal_points]]
    x = 6.2 #6.1
    y = 2.2