max_velocity = 1.5 #m/s 3.0
max_acceleration = 1.5 #m/s 2.75
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02 #FIXME point is from end of floor node to center of robot measured on practice bot
    y = 4.895
    angle = 0.0

[end_pose]
    x = 7.0 #7.07
    y = 4.58
    angle = 0.0

[[internal_points]]
    x = 4.5
    y = 4.737