max_velocity = 3.0 #m/s
max_acceleration = 2.75 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.07
    y = 4.58
    angle = 180.0

[end_pose]
    x = 2.02 
    y = 4.42
    angle = 180.0

[[internal_points]]
    x = 4.5
    y = 4.63