max_velocity = 1.0 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02 
    y = 4.42 
    angle = 0.0
[end_pose]
    x = 4.51 
    y = 3.3
    angle = 0.0

[[internal_points]]
    x = 2.81
    y = 3.9
