max_velocity = 1.5 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02 #FIXME measured for comp robot 
    y = 2.18
    angle = 0.0

[end_pose]
    x = 6.8587 #5.35 #test
    y = 2.18
    angle = 0.0

[[internal_points]]
    x = 3.5
    y = 2.18