max_velocity = 2.0 #m/s 3.0
max_acceleration = 2.0 #m/s 2.75
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.0 # 7
    y = 4.68 # cube 2
    angle = 180.0

[end_pose]
    x = 2.02 # 7
    y = 4.42 # cube 2 place mid
    angle = 180.0

[[internal_points]]
    x = 4.5
    y = 4.737