max_velocity = 2.75 #m/s
max_acceleration = 2.75 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 2.02 
    y = 4.895
    angle = 0.0

[end_pose]
    x = 6.80 # 7
    y = 3.16 # cube 3
    angle = 0.0

[[internal_points]]
    x = 5.5
    y = 5.12 

[[internal_points]]
    x = 6.0
    y = 3.97