max_velocity = 3.0 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.75 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.07
    y = 0.92
    angle = 180.0

[end_pose]
    x = 2.12
    y = 1.07 #1.07
    angle = 180.0

[[internal_points]]
    x = 4.5 #guess
    y = 0.752702 #guess