max_velocity = 3.25 #m/s
max_acceleration = 3.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.5 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose] 
    x = 6.90 # 7
    y = 4.58 # cube 4
    angle = 180.0

[end_pose]
    x = 2.12 # 7
    y = 4.42 # cube 4 place mid  3.82
    angle = 180.0

[[internal_points]]
    x = 4.5
    y = 4.85