max_velocity = 1.5 #m/s
max_acceleration = 1.5 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 7.07
    y = 0.909702
    angle = 0

[end_pose]
    x = 2.48
    y = 1.069702
    angle = 0

[[internal_points]]
    x = 4.5
    y = 0.739702