max_velocity = 1.5 #m/s
max_acceleration = 2.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.3 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 0.3
    y = 0.0
    angle = 180.0
[end_pose]
    x = 0.1
    y = 0.0
    angle = 180.0

[[internal_points]]
    x = 0.2
    y = 0.0
